<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <PackageReference Include="EFCore.NamingConventions" />
	  <PackageReference Include="MimeKit" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	  <PackageReference Include="Serilog.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
