<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>
</Project>
